### ISSUE TITLE
checkip.py loop logic issue

### ISSUE THREAD

**Issue by paulcimino** [radioactivetobi/geo-recon#2]
checkIP.py loop at the end of the code block does not allow for abuseConfidenceScore == 20.  If it is exactly 20 it will fall through the if statements and return no result.  Suggest changing the third elif statement to:

 elif json.dumps(decodedResponse ["data"]["abuseConfidenceScore"]) <= "20":

**Comment by radioactivetobi** [comment]
Thanks for your observation, I'll get this fixed promptly.
