### ISSUE TITLE
Daily rate limit of 1000 requests exceeded for this endpoint. See headers for additional details.

### ISSUE THREAD

**Issue by cabiamdos** [radioactivetobi/geo-recon#5]
Hello 

I am running this tool on kali linux and I am getting this error:
"Daily rate limit of 1000 requests exceeded for this endpoint. See headers for additional details."
![image](https://user-images.githubusercontent.com/82284393/212501134-f5cf6b8e-642a-4d29-a7f3-a59a104fb91d.png)

Any ideas?

**Comment by radioactivetobi** [comment]
This has been fixed with the lasted PR
